###
POST http://localhost:5000/api/v2/superheroes/superhero
Content-Type: application/json

{
  "superhero":"uravity",
  "realname": "urara"
}

###
GET http://localhost:5000/api/v2/superheroes HTTP/1.1


###
GET http://localhost:5000/api/v2/superheroes/6243a9cc720ac2c31bd7f451 HTTP/1.1


###
PUT  http://localhost:5000/api/v2/superheroes/6243a9cc720ac2c31bd7f451 HTTP/1.1
Content-Type: application/json

{
  "realname":"uraraka"
}


###
DELETE  http://localhost:5000/api/v2/superheroes/6243a9cc720ac2c31bd7f451 HTTP/1.1




###
POST http://localhost:5000/api/v2/newSuperheroes/newSuperhero HTTP/1.1
Content-Type: application/json

{
  "superhero":"daredevil",
  "identity":[{
    "realname": "matt murdock",
    "profession": "lawyer"
  }],
  "universe": "Marvel",
  "gadgets":[{
    "weapon": "sticks",
    "extra": "shurikens",
    "mask": "devil"
  }]
}


###
GET http://localhost:5000/api/v2/newSuperheroes/ HTTP/1.1


###
GET http://localhost:5000/api/v2/newSuperheroes/6243ab1b2864644e42443093 HTTP/1.1


###
PUT  http://localhost:5000/api/v2/newSuperheroes/6243ab1b2864644e42443093 HTTP/1.1
Content-Type: application/json

{
  "superhero":"daredevil",
  "identity":[{
    "realname": "matt murdock",
    "profession": "lawyer"
  }],
  "universe": "my hero academia",
  "gadgets":[{
    "weapon": "dagger",
    "extra": "bombs",
    "mask": "bandana"
  }]
}



###
DELETE  http://localhost:5000/api/v2/newSuperheroes/6243ab1b2864644e42443093 HTTP/1.1
